### ISSUE TITLE
Add language organization

### ISSUE THREAD

**Issue by henryiii** [iris-hep/awesome-hep#4]
This currently mixes all languages (at least Go, C++, Python), where most users will probably be looking for a tool in their current language. There should either be a top-level organization for languages, or a marker for each language in the list.

**Comment by jpivarski** [comment]
I had thought about splitting by language only for the very technical stuff, but you're right: it doesn't help a user much to learn that there's a tool for what they want, but it's in a different language. (The key word is "much," since there are ways of dealing with it, but it's an extra problem to solve.)
